spring:
  application:
    name: beneficios-api
  
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
  

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    com.beneficio.backend: DEBUG
    com.beneficio.ejb: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.springframework.orm: DEBUG
