CREATE TABLE BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  VALOR DECIMAL(15,2) NOT NULL,
  ATIVO BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0
);

CREATE TABLE TRANSFERENCIA (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BENEFICIO_ORIGEM_ID BIGINT NOT NULL,
  BENEFICIO_DESTINO_ID BIGINT NOT NULL,
  VALOR DECIMAL(15,2) NOT NULL,
  DATA_TRANSFERENCIA TIMESTAMP NOT NULL,
  OBSERVACOES VARCHAR(255),
  FOREIGN KEY (BENEFICIO_ORIGEM_ID) REFERENCES BENEFICIO(ID),
  FOREIGN KEY (BENEFICIO_DESTINO_ID) REFERENCES BENEFICIO(ID)
);
